language: objective-c
osx_image: xcode9
env:
  global:
    - WORKSPACE="iCalKit.xcodeproj"
    - IOS_FRAMEWORK_SCHEME="iCalKit-iOS"
    - OSX_FRAMEWORK_SCHEME="iCalKit-macOS"
    - TVOS_FRAMEWORK_SCHEME="iCalKit-tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="iCalKit-watchOS"
    - IOS_SDK=iphonesimulator11.0
    - OSX_SDK=macosx10.13
    - TVOS_SDK=appletvsimulator11.0
    - WATCHOS_SDK=watchsimulator4.0
  matrix:
    - DESTINATION="OS=11.0,name=iPhone 5s"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
    - DESTINATION="OS=11.0,name=iPhone 6"            SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
    - DESTINATION="OS=11.0,name=iPhone 6s"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
    - DESTINATION="arch=x86_64"                      SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"
    - DESTINATION="OS=11.0,name=iPhone 7"            SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
    - DESTINATION="OS=11.0,name=Apple TV 1080p"      SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"
    - DESTINATION="OS=4.0,name=Apple Watch - 38mm"   SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK"
script:
  - xcodebuild -project "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty
notifications:
    email:
          on_success: never
